name: Java CICD with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub Action'ı başlatmak için Repository’yi clone et
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. JDK kurulumunu yap
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # 3. Maven'ı kullanarak bağımlılıkları yükle ve projeyi build et
    - name: Build with Maven
      run: mvn clean install

    # 4. Selenium UI testlerini çalıştır
    - name: Run Selenium UI Tests
      run: mvn test
